version: "3.8"

services:
  app:
    build:
      context: ./app
    container_name: app
    ports:  
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - .env 
    volumes: 
      - ./app:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
