version: "3.8"

services:
  app:
    build:
      context: ./python
    container_name: app
    # ports:  
      # - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env 
    volumes: 
      - ./python:/app
    working_dir: /app
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env 
    # ports:
      # - "3306:3306"
# データ永続化設定
    # volumes:　　　
      # - mysql_data:/var/lib/mysql

# volumes:
  # mysql_data:

  nginx:
    image: nginx:latest
    container_name: nginx
    #ローカルだけで公開
    ports:
    - "127.0.0.1:80:80"
    #グローバルで公開
    # ports:
    #   - "127.0.0.1:80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      - app