# Generated by Django 4.2.23 on 2025-08-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_matchings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='star_rating_average',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1),
        ),
    ]
