# Generated by Django 4.2.23 on 2025-08-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_userprofile_star_rating_average'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
